name: Run Enrichment Process

on:
  workflow_run:
    workflows: ["Update NVD Data"]
    types:
      - completed
  workflow_dispatch:
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r code/requirements.txt
    
    - name: Run Enrichment Process
      run: |
        python -u code/enrich_nvd.py

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Commit and push if there are changes
      run: |
        git add .
        git commit -m "Updated CVSS-BT data $(date +%Y-%m-%d)" -a || exit 0
        git push

    - name: Tag commits
      run: |
        git tag -a "v0.1.0-$(date +%Y.%m.%d)" -m "Tagging commits for publish workflow"
        git push --tags
