name: Check for new EPSS data

on:
    schedule:
      - cron: "0 11-16 * * *" # Every day from 11am to 4pm UTC, 7am to 12pm EST
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-epss:
        runs-on: ubuntu-latest
        steps:
        - name: Check EPSS scores
          run: |
            TZ=America/New_York
            today=$(date +%Y-%m-%d)
            url="https://epss.cyentia.com/epss_scores-${today}.csv.gz"
            echo $url
            response=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            echo $response
            if [ "$response" -eq 200 ]; then
                echo "EPSS scores available for today"
            else
                echo "EPSS scores not available yet for today"
                exit 1
            fi
