name: Update NVD Data

on:
  workflow_run:
    workflows: ["Get EPSS Data"]
    types:
      - completed

permissions:
    contents: write
    
jobs:
    update-data:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            lfs: true
        
        - name: Checkout LFS objects
          run: git lfs checkout
        
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r code/requirements.txt

        - name: Process NVD Data
          run: |
            mkdir -p data/nvd
            python -u code/update_nvd.py
            python -u code/process_nvd.py
          env:
            NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

        - name: setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

        - name: Commit and Push Changes
          run: |
              git add .
              git commit -m "Updated NVD data $(date +%Y-%m-%d)"
              git push
